services:
  db:
    container_name: stella_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
      MYSQL_DATABASE: stella
    ports:
      - 3306:3306
    networks:
      - my_network

  next-app:
    depends_on:
      - db
    container_name: next-app
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    driver: bridge
