services:
  db:
    container_name: stella_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123123123
    ports:
      - 3306:3306
    networks:
      - my_network

  next-app:
    depends_on:
      - db
    container_name: next-app
    build:
      context: .
      dockerfile: dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        AUTH_SECRET: ${AUTH_SECRET}

    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    driver: bridge
