import type { Metadata } from "next";
import { mulish } from "./ui/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Stella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mulish.className} antialiased`}>{children}</body>
    </html>
  );
}
