import { ThemeProvider } from "@/app/ui/theme-provider";
import type { Metadata } from "next";
import { mulish } from "./ui/fonts";

import "./globals.css";

export const metadata: Metadata = {
  title: "Stella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${mulish.className} antialiased bg-white dark:bg-[#2d2d3d]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex justify-center items-center w-full px-32">
            <div className="flex flex-col gap-2 justify-start items-start w-full overflow-hidden">
              <h1 className="text-3xl font-bold mb-3 text-button">Stella</h1>
              <p className="text-lg font-light text-gray-400 dark:text-white/70 mb-4">
                Your Cosmic Guide to Love, Life, and Connection
              </p>
              <div className="flex flex-col gap-4">
                <div>
                  <h2 className="text-xl font-semibold text-button">
                    Discover
                  </h2>
                  <p className="text-sm text-gray-400/90 dark:text-white/60">
                    Start your day with personalized AI-generated horoscopes and
                    insights tailored to your zodiac sign.
                  </p>
                </div>

                <div>
                  <h2 className="text-xl font-semibold text-button">Connect</h2>
                  <p className="text-sm text-gray-400/90 dark:text-white/60">
                    Dive into compatibility reports to understand how your
                    relationships align and how to nurture them.
                  </p>
                </div>

                <div>
                  <h2 className="text-xl font-semibold text-button">Empower</h2>
                  <p className="text-sm text-gray-400/90 dark:text-white/60">
                    Navigate life&apos;s challenges with daily guidance,
                    powerful insights, and actionable tips to stay aligned with
                    your cosmic path.
                  </p>
                </div>
              </div>
            </div>
            <div className="min-w-[390px] max-w-[390px] h-full overflow-y-scroll scrollbar-hide border-l-2 border-gray-300 dark:border-white/5">
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
