name: GitHub Actions Deployment
run-name: ${{ github.actor }} is deploying GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, Linux, X64, jay]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Change executable mode
        run: sudo chmod +x run.sh
      - name: Run deployment script
        run: ./run.sh
