name: GitHub Actions Deployment
run-name: ${{ github.actor }} is deploying GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, Linux, X64, jay]
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Change executable mode
        run: sudo chmod +x run.sh
      - name: Run deployment script
        run: ./run.sh
